name: Format

on:
  pull_request:
    branches:
      - main
      - 2024-beta

jobs:

  formatting:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: axel-op/googlejavaformat-action@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          args: "--skip-sorting-imports --replace"
